name: Playwright Tests
on:
  workflow_dispatch:  # Allows manual triggering and API usage
  push:
    branches: [ main, development ]
jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1  # Skip downloading unnecessary browsers
      run: npm ci
    - name: Install Chromium Browser
      run: npx playwright install chromium  # Install only Chromium
    - name: Run Playwright tests
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME_WRONG: ${{ secrets.USERNAME_WRONG }}
        USERNAME_LOCKED: ${{ secrets.USERNAME_LOCKED }}
        PASSWORDEMAILSEND: ${{ secrets.PASSWORDEMAILSEND }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30